### ISSUE TITLE
Rewind 30s Button

### ISSUE THREAD

**Issue by SurreyMichael** [iantrich/podcast-card#10]
It would be really useful to be able to add a 'rewind 30 seconds' button to a lovelace card in Home Assistant.

Ideally something that works through mini-media-player. This already shows a progress bar which does allow scrubbing through a podcast, but is clumsy to use especially on mobile rather than desktop.

Describe alternatives you've considered
Learn mindfulness so that I concentrate better during podcasts and don't miss the interesting bits.

**Comment by iantrich** [comment]
I have a partial solution more or less ready to go which allows you to pass down the configuration for the mini-media-player so that you can do this
```yaml
type: 'custom:podcast-card'
entity: sensor.gpodder
name: Ian's Podcasts
show_player: true
custom_player: true
player_config:
    shortcuts:
    buttons:
        - type: script
        id: skip
        icon: mdi:rewind-30
        data: media_player.bedroom
        interval: -30
        - type: script
        id: skip
        icon: mdi:fast-forward-30
        data: media_player.bedroom
        interval: 30
```
Then setup your script as described here: community.home-assistant.io/t/lovelace-mini-media-player/68459/1218

The only limitation with this is that you'll have to hardcode the media_player that the script calls. I'll look into providing some variables possibly to work around that in another release and will push this out after I get home and test it a bit.
